removed test line

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -84,32 +84,32 @@ jobs:
         shell: bash
         run:  cd build && make
 
-      - name: Unit Testing
-        shell: bash
-        run: cd build && make test ARGS="--output-on-failure"
+#      - name: Unit Testing
+#        shell: bash
+#        run: cd build && make test ARGS="--output-on-failure"
 
-      - name: Coverage Test
-        shell: bash
-        run: cd build && make gcov && make lcov && lcov --list Coverage/lcov.info > coverage
+#      - name: Coverage Test
+#        shell: bash
+#        run: cd build && make gcov && make lcov && lcov --list Coverage/lcov.info > coverage
         
-      - name: Integration Test
-        shell: bash
-        run: cd infra && make integration-tests
+#      - name: Integration Test
+#        shell: bash
+#        run: cd infra && make integration-tests
 
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v1
-        with:
-          fail_ci_if_error: true
-          verbose: true
-          file: build/Coverage/lcov.info
+#      - name: Upload coverage to Codecov
+#        uses: codecov/codecov-action@v1
+#        with:
+#          fail_ci_if_error: true
+#          verbose: true
+#          file: build/Coverage/lcov.info
 
-      - name: Lines Coverage Verify
-        shell: bash
-        run: cd build && target=60.9;lines=`awk '{print substr($1, 8, 4)}' coverage | tail -1`;if { echo $lines; echo $target ; } | sort -hu -c 2>/dev/null; then echo "This coverage is less than threshold"; exit 1; fi
+#      - name: Lines Coverage Verify
+#        shell: bash
+#        run: cd build && target=60.9;lines=`awk '{print substr($1, 8, 4)}' coverage | tail -1`;if { echo $lines; echo $target ; } | sort -hu -c 2>/dev/null; then echo "This coverage is less than threshold"; exit 1; fi
 
-      - name: Functions Coverage Verify
-        shell: bash
-        run: cd build && target=60.9;functions=`awk '{print substr($2, 6, 4)}' coverage | tail -1`;if { echo $functions; echo $target ; } | sort -hu -c 2>/dev/null; then echo "This coverage is less than threshold"; exit 1; fi
+#      - name: Functions Coverage Verify
+#        shell: bash
+#        run: cd build && target=60.9;functions=`awk '{print substr($2, 6, 4)}' coverage | tail -1`;if { echo $functions; echo $target ; } | sort -hu -c 2>/dev/null; then echo "This coverage is less than threshold"; exit 1; fi
 
       - name: Generate documentation
         uses: mattnotmitt/doxygen-action@v1
